# Generated by Django 6.0.1 on 2026-03-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_language'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='game_questi_categor_365b13_idx',
            old_name='game_question_cat_lang_idx',
        ),
    ]
